version: '3'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - db
    environment:
      - NODE_ENV=development
      # Add other environment variables as required for your app

  db:
    image: postgres
    environment:
      POSTGRES_DB: ketemuenak_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
